INSERT INTO DIGIT_USER(user_id, email, username) VALUES (1, 'lucascicutti1995@gmail.com', 'Lucas');
INSERT INTO DIGIT_USER(user_id, email, username) VALUES (7, 'jruas@gmail.com', 'Joao');
INSERT INTO DIGIT_USER(user_id, email, username) VALUES (4, 'arthurcf@gmail.com', 'Arthur');

INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (1, 2, 3, 1);
INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (1, 2, 2, 1);
INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (1, 2, 2, 1);

INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (3, 2, 6, 4);
INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (3, 2, 6, 4);

INSERT INTO UNIQUE_DIGIT(NUMBER_VALUE, MULTIPLIER, DIGIT_VALUE, USER_ID) VALUES (4, 2, 8, 7);

INSERT INTO WALLET(WALLET_ID, USER_NAME, USER_FUNDS) VALUES (1, 'lucascicutti1995@gmail.com', 10000);

