INSERT INTO DIGIT_USER VALUES (1, 'lucascicutti1995@gmail.com', 'Lucas');
INSERT INTO DIGIT_USER VALUES (2, 'jruas@gmail.com', 'Joao');
INSERT INTO DIGIT_USER VALUES (3, 'arthurcf@gmail.com', 'Arthur');

INSERT INTO UNIQUE_DIGIT VALUES (4, 1, 2, 33, 1);
INSERT INTO UNIQUE_DIGIT VALUES (5, 1, 2, 34, 1);
INSERT INTO UNIQUE_DIGIT VALUES (6, 1, 2, 35, 1);

INSERT INTO UNIQUE_DIGIT VALUES (7, 1, 2, 36, 2);
INSERT INTO UNIQUE_DIGIT VALUES (8, 1, 2, 37, 2);

INSERT INTO UNIQUE_DIGIT VALUES (9, 1, 2, 38, 3);